query publicMap ($id: String!) {
  publicMap(id: $id) {
    id
    name
    initialArea {
      latitude
      longitude
    }
    filters
    pins {
      id
      name
      data
      comment
      orderedFields
      location {
        latitude
        longitude
      }
    }
  }
}
